######################################################################
# @author      : neimv (neimv@dark-universe)
# @file        : Makefile
# @created     : lunes dic 28, 2020 12:31:01 CST
######################################################################

CFLAGS=-Wall -g
cc=gcc

all: clean ex02

ex02:
	$(cc) $(CFLAGS) ex02.c -o ex02

clean:
	rm -f ex01

