######################################################################
# @author      : neimv (neimv@dark-universe)
# @file        : Makefile
# @created     : domingo may 23, 2021 22:51:53 CDT
######################################################################


build:
	gcc -Wall -std=c99 ./src/*c -lSDL2 -o game

run:
	./game

clean:
	rm game

