######################################################################
# @author      : neimv (neimv@dark-world)
# @file        : Makefile
# @created     : domingo jun 13, 2021 19:39:33 CDT
######################################################################

all:
	dasm *.asm -f3 -v0 -ocart.bin -lcart.lst -scart.sym

run:
	stella cart.bin

clean:
	rm *.bin

