######################################################################
# @author      : neimv (neimv@dark-universe)
# @file        : Makefile
# @created     : lunes dic 28, 2020 12:31:01 CST
######################################################################

CFLAGS=-Wall -g
cc=gcc

all: clean ex01

ex01:
	$(cc) $(CFLAGS) ex01.c -o ex01

clean:
	rm -f ex01

